sudo: required
language: node_js
node_js:
- '14'
- '12'
- '10'
install:
- npm install lerna -g
- lerna bootstrap
script:
- lerna run compile
- lerna run test:coverage
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run coveralls; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run codacy; fi
env:
  global:
  - secure: gL8LAXeUAuBDFKfIWXZMONoMy0CNN5dUx7oYdEgtiPxgfSTazbrALzA56mLyL9wPw7Utr71uLvzuI0FvNN62oVGXj/1u3tVL0ALj5z62OeY58640zEgZbrL04CEyMewKoyjkxZ3+ForLs2L1ZyHcNDyJRgdMAHG2w+DvvWdmXgmVXEh/3KYir0IxHPQoj/HjKO/o9G2zSyEIoW9OpMNjQt4hhvrIbK3ZwHoDW+uxZYN5XZ3uxZZwkWpG87vp7uhOl6sGPjA2d20u48iPdM2hB4I0esJew5/jGZ0xSNCg/oiC/iegQ7LMnqVCB3NTdhSz6bw4TMi3bRM5npXNDFp8AkrbC5TAsVr4TqAoRzSQs3maLp3fmthuItLw4p6NAoyVMlOBfAryZtY/gn2I4yD71Qnr+owo2GqP6PsVaP3kO0d5RioDs8X9hNCt6MhG/vUxf2jqJQHI9YPBvCX0Xgq0emDCHF1O9mSbiMoBzJ1yTYTYd9IBnWpYKUAtfPlMg+W4HTkQTHYYFjGRP0OFKnlbVRO61AaIvnvRlv2XmAP9V6LSmN1v1J3czBCSbnL3jYKslI4gQTrJtUa9wqbE8eI/ro4wcKp1Qa56LylK/hGnbzB5QyYX30mIpN7lOyezmlD3OHiowAA3Z8rgG4ssw1D2/1aue/08CfMP//I0ccI0M6k=
  - secure: KW1rf7vXUsm9ssjKXVS2BfJf8zi7t2FUW9UYLDOJuhk5MtHm/+TQ6n/Z9vvbxgGXXxz3lXXMdOj/ZwD3RXyyAFE6KHTMm2nyzCYiGQlnhDVYaDCL8P1s9fj7Y/OcCSnGLw+LCW+B4pZyrZJkcCXXzd5M3Ux9a8G2aJGp0eF2wkWUZmk8tZDPpSrlhA+oAd9CuwuLBBmSbz7l0dJbQiZLtKNEh71wP7FsK6fu2qsw7iAox8frc8Tp9G+vkYczZN23qoC1v9pMrous+Ogmo4Rw3/DTCvz2DV5o2tUivBxuCS2CchKGkHolIrIdSpVIDPLiZAseJQkYEnkfrWQxO7z7HqDqI2RIzG+4Yu/Nnjf2Iscwy92IuX7IBT10aYp5sU9QOBq/HEQivmzBPnZKqp4o3zK+//tVJbUcPkPieKCEJ3DxdhCRGPsry9ZLS8we7gUF/7f/0jkcZfeAO9AyeVDCKrI2xyA4aIC5vmOjhLSIqsY8+UgaaUgqehb79wyLavJZ077O1wEY9Y1uFXWBjJuhz/jgbOpxvDPXI5BfAouVnpzwrEG10eDa2HN/VsXRNvIqddMtBAGFhdvJpp6v0LP+o8rrU+IlrtEP7LGHcZBA+QBul0eeBWgYZTwkZtMEyFyMjSZeP3cyaKwQ6yTz4yQw4DzmkK5Z388WvooZCEyS7MU=
branches:
  only:
  - "/.*/"
