sudo: required
language: node_js
node_js:
- '14'
- '12'
- '10'
install:
- npm install lerna -g
- lerna bootstrap
script:
- lerna run compile
- lerna run test:coverage
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run coveralls; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then lerna run codacy; fi
env:
  global:
  - secure: zJ5G8EPMO4n5/p9i0aHeGJpxTuI0H9DBPYsdCuEeqc8PlJzwz9I0dqmph39t8wiVCk46uPMzHPNxiVMi0h9Xcvc2073hW3d8EjeCfHrPqIGxQj1MXSdP6OHB5h98hbgWWqzfWvSZzb+gO9hhhbF6LNk8eGbwnyzYyDW/z02Y2ZAvswV/XbBbpALWBmJ8EnTemsqY57NmZZUgIuQHkngiVkKjOEzcfPO4jU5tfyTJdtDwfOh0UPLFFsOJ6K4ehBNHFG4ZjpHnq1GzXxA0ZNx5ypSh6HdEaNJ/zU9IokCMpG4QOY1M552IUZOJ29gQDADnhi3rLpHSos6z9RHMZ9laTRwatQS5geK2n6kmN+7dpoaoElv2h/UnJmJ4PK1qIeOEsjahOnhcX3Owd1maqtg/XWHceUdzG0kz/36RqwbR+yuWLt7E/LGOjHjG3054qFhAdvjS8BAt46ariYU1Z27Ze8Fm8ce9g2WBTKIDUZzOOwsdKMbWEDK3ly19QnkiNccVtdNFB2LJG9g7gD32vG4VnrIPSLVuuPjFVQkDMc0hyrVLv1O0oTjCHQMEUWe8qcSt49ozp18+eSuLP/9gAjDfB8mvsz4CBREvSuuYfCZ7aIJr+Fw6SyXK0iwb9l2tkLRzlsQF62P91y7hGok/JpUNPWaU3QAqDboKNCS7raswD6c=
  - secure: gL8LAXeUAuBDFKfIWXZMONoMy0CNN5dUx7oYdEgtiPxgfSTazbrALzA56mLyL9wPw7Utr71uLvzuI0FvNN62oVGXj/1u3tVL0ALj5z62OeY58640zEgZbrL04CEyMewKoyjkxZ3+ForLs2L1ZyHcNDyJRgdMAHG2w+DvvWdmXgmVXEh/3KYir0IxHPQoj/HjKO/o9G2zSyEIoW9OpMNjQt4hhvrIbK3ZwHoDW+uxZYN5XZ3uxZZwkWpG87vp7uhOl6sGPjA2d20u48iPdM2hB4I0esJew5/jGZ0xSNCg/oiC/iegQ7LMnqVCB3NTdhSz6bw4TMi3bRM5npXNDFp8AkrbC5TAsVr4TqAoRzSQs3maLp3fmthuItLw4p6NAoyVMlOBfAryZtY/gn2I4yD71Qnr+owo2GqP6PsVaP3kO0d5RioDs8X9hNCt6MhG/vUxf2jqJQHI9YPBvCX0Xgq0emDCHF1O9mSbiMoBzJ1yTYTYd9IBnWpYKUAtfPlMg+W4HTkQTHYYFjGRP0OFKnlbVRO61AaIvnvRlv2XmAP9V6LSmN1v1J3czBCSbnL3jYKslI4gQTrJtUa9wqbE8eI/ro4wcKp1Qa56LylK/hGnbzB5QyYX30mIpN7lOyezmlD3OHiowAA3Z8rgG4ssw1D2/1aue/08CfMP//I0ccI0M6k=
branches:
  only:
  - "/.*/"
